package pers.jess.template.answer.dao;

import pers.jess.template.answer.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //nt deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_user
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    //int updateByPrimaryKey(User record);

    User queryUserByPhone(String phone);
}