package pers.jess.template.answer.model;

import org.springframework.stereotype.Component;

@Component
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer_user.id
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer_user.username
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer_user.phone
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer_user.department
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer_user.job
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    private String job;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer_user.id
     *
     * @return the value of t_answer_user.id
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer_user.id
     *
     * @param id the value for t_answer_user.id
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer_user.username
     *
     * @return the value of t_answer_user.username
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer_user.username
     *
     * @param username the value for t_answer_user.username
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer_user.phone
     *
     * @return the value of t_answer_user.phone
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer_user.phone
     *
     * @param phone the value for t_answer_user.phone
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer_user.department
     *
     * @return the value of t_answer_user.department
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer_user.department
     *
     * @param department the value for t_answer_user.department
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer_user.job
     *
     * @return the value of t_answer_user.job
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer_user.job
     *
     * @param job the value for t_answer_user.job
     *
     * @mbggenerated Mon Jul 31 14:30:25 CST 2017
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }
}